### ISSUE TITLE
Out-of-prior bounds for `SLCP` posterior sampling on slurm

### ISSUE THREAD

**Issue by JuliaLinhart** [JuliaLinhart/benchmark_sbi#5] opened 2023-07-10 14:16 UTC
Out-of prior bounds issue when evaluating `log_joint` for the `slcp` dataset. 
Occurs within the `MetropolisHastings` sampler used for posterior sampling.

```terminal
Traceback (most recent call last):
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/runner.py", line 172, in run_one_solver
    skip, reason = objective.set_dataset(dataset)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/base.py", line 419, in set_dataset
    data = dataset._get_data()
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/base.py", line 300, in _get_data
    self._data = self.get_data()
  File "/data/parietal/store/work/jlinhart/git_repos/benchmark_sbi/datasets/slcp.py", line 101, in get_data
    samples = next(sampler(4096 + 1, burn=4096))
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/lampe/inference.py", line 779, in __iter__
    log_f_y = self.log_f(y)
  File "/data/parietal/store/work/jlinhart/git_repos/benchmark_sbi/datasets/slcp.py", line 94, in log_joint
    log_prior = prior.log_prob(theta)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/independent.py", line 99, in log_prob
    log_prob = self.base_dist.log_prob(value)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/uniform.py", line 80, in log_prob
    self._validate_sample(value)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/distribution.py", line 300, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (1024, 5)) to be within the support (Interval(lower_bound=tensor([-3., -3., -3., -3., -3.]), upper_bound=tensor([3., 3., 3., 3., 3.]))) of the distribution Uniform(low: torch.Size([5]), high: torch.Size([5])), but found invalid values:
tensor([[ 1.1010,  2.0457,  1.7297, -2.3728, -3.0825],
        [-0.6580, -1.7074, -1.3019, -1.1818, -2.4541],
        [-0.7172,  0.0380, -1.6950,  4.1641,  1.5258],
        ...,
        [-3.1576, -3.8259,  1.6329,  1.8041, -1.7510],
        [-2.5842, -0.6191,  1.1303, -4.0777, -1.4203],
        [ 2.7926, -1.1439,  0.4714, -4.9117, -0.1293]])
```

**Comment by francois-rozet** [comment] 2023-07-11 08:00
Ah right I forgot about that. That is not actually an issue, it is just that PyTorch, by default, checks whether values are within the support of a distribution before evaluating the `log_prob`. This behavior can be disabled such that log prob returns $-\infty$. What is weird is that I thought I had disabled that within Zuko already, so importing `lampe` should also disable it.

**Comment by JuliaLinhart** [comment] 2023-07-11 08:19
Here it happens when evaluating the `prior.log_prob` withing the `get_data` function, which does not depend on `zuko` (or lampe) implementations .

**Comment by JuliaLinhart** [comment] 2023-07-11 08:22
I'll let you fix it @francois-rozet ? :)

**Comment by francois-rozet** [comment] 2023-07-11 08:30
> Here it happens when evaluating the `prior.log_prob` within the `get_data` function, which does not depend on `zuko` (or lampe) implementations .

`lampe` is imported at the top of the file, and itself imports `zuko`, which should be enough to prevent the support checks.

> I'll let you fix it @francois-rozet ?

Sure, but I am not able to reproduce the bug :sweat_smile: Does it appear when you run `benchopt run -d slcp` or when you launch the tests?

**Comment by JuliaLinhart** [comment] 2023-07-11 08:36
It appears when I run it on `slurm`! Here's the whole error log: 
```

Posterior sampling:   0%|          | 0/16 [00:00<?, ?it/s]
Posterior sampling:   0%|          | 0/16 [00:00<?, ?it/s]
submitit ERROR (2023-07-11 10:34:17,773) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/runner.py", line 172, in run_one_solver
    skip, reason = objective.set_dataset(dataset)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/base.py", line 419, in set_dataset
    data = dataset._get_data()
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/benchopt/base.py", line 300, in _get_data
    self._data = self.get_data()
  File "/data/parietal/store/work/jlinhart/git_repos/benchmark_sbi/datasets/slcp.py", line 101, in get_data
    samples = next(sampler(4096 + 1, burn=4096))
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/lampe/inference.py", line 779, in __iter__
    log_f_y = self.log_f(y)
  File "/data/parietal/store/work/jlinhart/git_repos/benchmark_sbi/datasets/slcp.py", line 94, in log_joint
    log_prior = prior.log_prob(theta)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/independent.py", line 99, in log_prob
    log_prob = self.base_dist.log_prob(value)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/uniform.py", line 80, in log_prob
    self._validate_sample(value)
  File "/data/parietal/store/work/jlinhart/miniconda3/envs/benchsbi/lib/python3.9/site-packages/torch/distributions/distribution.py", line 300, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (1024, 5)) to be within the support (Interval(lower_bound=tensor([-3., -3., -3., -3., -3.]), upper_bound=tensor([3., 3., 3., 3., 3.]))) of the distribution Uniform(low: torch.Size([5]), high: torch.Size([5])), but found invalid values:
tensor([[ 1.1010,  2.0457,  1.7297, -2.3728, -3.0825],
        [-0.6580, -1.7074, -1.3019, -1.1818, -2.4541],
        [-0.7172,  0.0380, -1.6950,  4.1641,  1.5258],
        ...,
        [-3.1576, -3.8259,  1.6329,  1.8041, -1.7510],
        [-2.5842, -0.6191,  1.1303, -4.0777, -1.4203],
        [ 2.7926, -1.1439,  0.4714, -4.9117, -0.1293]])
srun: error: margpu006: task 0: Exited with exit code 1
```

**Comment by francois-rozet** [comment] 2023-07-11 08:45
This is likely a `submitit` related error then. Can you give me the slurm config files?

**Comment by JuliaLinhart** [comment] 2023-07-11 08:56
Yes, here you go. 
```
slurm_time: 01:00:00        # max runtime 1 hour
slurm_gres: gpu:1           # requires 1 GPU per job
slurm_additional_parameters:
  ntasks: 1                 # Number of tasks per job
  partition: gpu  # Partition
  cpus-per-task: 40         # requires 40 CPUs per job
  qos: normal             # Queue used for the jobs
  distribution: block:block # Distribution on the node's architecture
```

And the command line to reproduce the error:

`benchopt run benchmark_sbi --slurm slurm_config.yml -d slcp`

**Comment by francois-rozet** [comment] 2023-07-11 13:01
It is indeed an issue with `submitit`. The following script raises an error at the first line of `f()`.

```python
import submitit
import torch

torch.distributions.Distribution._validate_args = False

def f():
    assert not torch.distributions.Distribution._validate_args, "nok"
    assert False, "ok"

executor = submitit.AutoExecutor("dump")

job = executor.submit(f)
job.result()
```

I don't know `submitit` well enough to understand why this happens, but I guess it is due to the code's pickling. Maybe we can ask Thomas?

**Comment by JuliaLinhart** [comment] 2023-07-11 15:32
Issue solved when setting `torch.distributions.Distribution._validate_args = False` within the `objective.py` file. 
If I got it right, this is because the jobs originate from this file and won't take into account global settings from other files.

**Comment by francois-rozet** [comment] 2023-07-12 08:05
Reopening until #6 is merged.

**Comment by francois-rozet** [comment] 2023-07-12 09:04
So I did some more tests, and it is even weirder than I thought. The previous script (see https://github.com/JuliaLinhart/benchmark_sbi/issues/5#issuecomment-1630787850) failed because `lampe` (or `zuko`) was not used in `f()`. The following, on the other hand, works like a charm (note that `zuko.distributions.Distribution` is the same class as `torch.distributions.Distribution`).

```python
import submitit
import zuko

assert not zuko.distributions.Distribution._validate_args

def f():
    assert not zuko.distributions.Distribution._validate_args

executor = submitit.AutoExecutor("dump")

job = executor.submit(f)
job.result()
```

However, with an equivalent dummy dataset

```python
from benchopt import BaseDataset, safe_import_context

with safe_import_context() as import_ctx:
    import zuko

    assert not zuko.distributions.Distribution._validate_args


class Dataset(BaseDataset):
    name = "dummy"
    parameters = {}

    def get_data(self):
        assert not zuko.distributions.Distribution._validate_args
```

running Benchopt on slurm leads to an error.

```
$ benchopt run -d dummy -s nre_lampe --slurm slurm_config.yml
Benchopt is running
Running on SLURM
...
  File "/home/frozet/benchmark_sbi/datasets/dummy.py", line 14, in get_data
    assert not zuko.distributions.Distribution._validate_args
AssertionError
```

So in the end, the issue is not `submitit` but something within Benchopt.

**Comment by JuliaLinhart** [comment] 2023-07-12 09:25
I it works if you write the line  `torch.distributions.Distribution._validate_args = False` within the `Dataset` class or in the `objective.py` file. It doesn't work if you write it in the `slcp.py` file outside of the `Dataset` class. 

So my guess is that it would work if you import `zuko` within the `Dataset` class. 

Anyways Thomas said that there is something going wrong aswell. I'll create an issue for him in `benchopt`.

**Comment by francois-rozet** [comment] 2023-07-12 11:33
Ok I found the error... The issue is that `pyro`, which is imported by `sbibm`, sets the `torch.distributions.Distribution._validate_args` to `True`. If `pyro` is imported prior to `zuko`, this is not an issue, but with `submitit` (and `cloudpickle`) the packages are not necessarily (re-)imported in the same order as written in the file. For instance, this fails:

```python
import submitit
import pyro
import zuko

assert not zuko.distributions.Distribution._validate_args

def f():
    assert not zuko.distributions.Distribution._validate_args  # error :(
    print(pyro)

executor = submitit.AutoExecutor("dump")

job = executor.submit(f)
job.result()
```

So it is not a bug of Benchopt, no need to file an issue.

**Comment by JuliaLinhart** [comment] 2023-07-12 12:10
Nice catch! Thanks!

**Closed as completed** 2023-07-13 08:55 UTC
